name: "trading_analytics_dbt"
version: "1.0"
config-version: 2

profile: "trading_analytics_dbt"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  trading_analytics_dbt:
    +materialized: table
    +on_schema_change: sync_all_columns
    #gold:
      #+schema: gold
      
